server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php;
    client_max_body_size 100M;

    location /public/ {
        alias /var/www/html/public/;
    }

    location / {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $request_uri;
        include fastcgi_params;
    }
}
